---
# Source: data-space-connector/charts/scorpio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-scorpio
  namespace: "provider"
  labels:
    helm.sh/chart: scorpio-0.4.7
    app.kubernetes.io/name: scorpio
    app.kubernetes.io/instance: provider
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scorpio
      app.kubernetes.io/instance: provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scorpio
        app.kubernetes.io/instance: provider
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: scorpio
          securityContext:
            {}
          image: "scorpiobroker/all-in-one-runner:java-4.1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /q/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
    
          env:
            - name: DBHOST
              value: data-service-postgis
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: postgres-admin-password
            - name: DBUSER
              value: postgres
            - name: POSTGRES_DB
              value: data-service-postgis
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: postgres-admin-password
            - name: POSTGRES_USER
              value: postgres  
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: QUARKUS_LOG_LEVEL
              value: "INFO"
          resources:
            {}
      volumes:
      - configMap:
          defaultMode: 493
          name: scorpio-registration
        name: scorpio-registration
